# Generated by Django 4.0 on 2022-03-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQuiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
