# Generated by Django 4.0 on 2022-03-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQuiz', '0002_quiz_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='image',
        ),
        migrations.AddField(
            model_name='quiz',
            name='imageurl',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
